export ROLE=developer
.PHONY:environment
environment:
	cd ../../../workspaces && CON_GEOM="63x40" con "../system/bin/rde"

.PHONY:environment_odaba
environment_odaba:
	cd ../../../workspaces/auxiliary/odaba  && make buildshell

.PHONY:manage
manage:
	CON_GEOM="135x43+430+10" con "/data/scripts/m"


